
spring:
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000s
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true

  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /
  port: 8001

